name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install debhelper python3 python3-distutils-extra

    - name: Build Debian package
      run: dpkg-buildpackage -b -us -uc

    - name: Move deb packages
      run: mkdir packages && mv ../*.deb packages/
      
    - uses: actions/upload-artifact@v1
      with:
        name: Debian packages
        path: packages
    - name: Deploy - Create directory
      uses: ysurac/ssh-action@master
      with:
        command: |
          mkdir -p deploy/debian
        host: ${{ secrets.OMR_DEPLOY_HOST }}
        user: deploy
        port: ${{ secrets.OMR_DEPLOY_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        args: -tt
    - name: Deploy - Upload via rsync
      uses: ysurac/action-rsync@master
      env:
        ARGS: -av
        TARGET: deploy/package
        SOURCE: ./packages/
        KEY: ${{ secrets.PRIVATE_KEY }}
        USER: deploy
        HOST: ${{ secrets.OMR_DEPLOY_HOST }}
        PORT: ${{ secrets.OMR_DEPLOY_PORT }}